name: Publish

on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      uses: actions/checkout@v2

    - name: Set output tag
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: Login Reistry
      if: ${{ github.event_name != 'pull_request' || ! github.event.pull_request.head.repo.fork }}
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - id: Setup pack
      uses: buildpacks/github-actions/setup-pack@v4.4.0

    - id: Build & Publish
      run: |
        #!/usr/bin/env bash
        set -euo pipefail
        pack build ${REPO}:${{RELEASE_VERSION}}   \
          --tag ${REPO}:latest                    \
          --buildpack paketo-buildpacks/go        \
          --builder paketobuildpacks/builder:tiny \
          --publish     
      shell: bash
      env:
        REPO: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
